### ISSUE TITLE
explicit pin of bisect_ppx.1.0.0 precludes use by ocaml > 4.02.3

### ISSUE THREAD

**Issue by yomimono** [simonjbeaumont/ocaml-travis-coveralls#11]
If it's necessary to pin a particular version, is it possible to use a later one?

**Comment by aantron** [comment]
It would be best not to pin to a particular version. A major cause of Bisect_ppx releases is new OCaml releases, when they modify the AST. This means Bisect_ppx versions don't, in general, have forward compatibility.

**Comment by simonjbeaumont** [comment]
I originally had this because I wanted other people to track master of this repo (like the ocaml-ci-skeleton files) by just `wget`ing it and running it. As such I wanted to nail it down as much as possible to a set I _knew_ worked. With the utmost respect for bisect_ppx, I wanted to buffer this project against a bug in that repo or breaking because of a major interface change.

I think I nailed it down because there was such a change (I think the reporting binary moved from one version to the next).

I'm happy to update to a newer version which would not preclude using a newer OCaml version. I'll try and find some time this week.

**Comment by simonjbeaumont** [comment]
Oh, and this repo has it's own CI now so feel free to submit a PR.

**Comment by simonjbeaumont** [comment]
@aantron I assume newer versions of bisect-ppx build with older versions of OCaml 4.02.x?

**Comment by simonjbeaumont** [comment]
This is my concern:

```bash
$ opam info bisect_ppx | grep depends
             depends: ocamlfind & ppx_tools >= 4.02.3 & ocamlbuild & cppo
```

By moving to a newer version I prohibit people from building projects that use OCaml < 4.02.3.

Any suggestions?

**Comment by simonjbeaumont** [comment]
Oh, maybe I'm mistaken. I thought there'd be a 1:1 mapping from `ppx_tools` to compiler version but it looks like `ppx_tools.4.02.3` is available for `ocaml-version >= "4.02.0" & ocaml-version < "4.03.0"`

**Comment by aantron** [comment]
> With the utmost respect for bisect_ppx, I wanted to buffer this project against a bug in that repo or breaking because of a major interface change.

Fair enough. The report tool didn't move during my watch. Not sure about before that, I guess it was renamed to its current name at some point.

We are planning an interface change (in planned version 2.0.0). Other than that, we avoid making them, except dropping some features that we were 99.999% sure nobody used (obscure output formats and the like).

As for bugs and mistaken breakage, of course it's possible, but Bisect_ppx is armed with a pretty thorough test suite, two maintainers, and runs on itself for coverage. It might actually help us to catch mistakes faster if you allow any Bisect_ppx < 2.0.0, and let people complain :)

Alternatively, we can make it part of the Bisect_ppx release process to notify you, so you can bump the version from time to time.

> I assume newer versions of bisect-ppx build with older versions of OCaml 4.02.x?

Yes, 1.2.0 will build with any OCaml after 4.02 (i.e. that supports PPX). As you already found, the `ppx_tools` 4.02.3 was a marketing number. That version actually supports all of 4.02. Indeed, there was a discussion about *not* numbering `ppx_tools` in this way (https://github.com/alainfrisch/ppx_tools/issues/35).

**Comment by simonjbeaumont** [comment]
@aantron thanks for that explanation. I've updated to `bisect_ppx.1.2.0`. I'll open another PR when I work out the runes for doing an `opam install` with upper and lower version bounds.
